CREATE TABLE BOOK(
	BOOK_ID			NUMBER,
	CONCERT_ID		NUMBER	NOT NULL,
	MEMBER_ID		VARCHAR2(50)	NOT NULL,
	BOOK_ETICKET	VARCHAR2(20)	NOT NULL,
	BOOK_AMOUNT		NUMBER	NOT NULL,
	CARD_ID			VARCHAR2(20)	NOT NULL,
	BOOK_DATE		DATE	NOT NULL,
	BOOK_PAYMENT    NUMBER,
	PRIMARY KEY(BOOK_ID),
	FOREIGN KEY(CONCERT_ID) REFERENCES CONCERT(CONCERT_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	FOREIGN KEY(CARD_ID) REFERENCES CARD(CARD_ID)
);
create sequence book_seq;

SELECT * FROM BOOK;
DELETE FROM BOOK;
