drop table card;
CREATE TABLE CARD(
	CARD_ID		VARCHAR2(20),
	MEMBER_ID	VARCHAR2(50)	NOT NULL,
	CARD_MMYY	NUMBER	NOT NULL,
	CARD_CVV	NUMBER	NOT NULL,
	PRIMARY KEY(CARD_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);


SELECT * FROM CARD;
DELETE FROM CARD;
