CREATE TABLE CHAT(
	CHAH_LOG_ID			VARCHAR2(20),
	MEMBER_ID			VARCHAR2(20)	NOT NULL,
	CHAR_LOG_ANSWER		VARCHAR2(100),
	CHAH_LOG_CONTENT	VARCHAR2(100)	NOT NULL,
	CHAR_LOG_DATE		DATE	NOT NULL,
	PRIMARY KEY(CHAH_LOG_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER
);

create sequence chat_seq increment by 1 start with 1;
SELECT * FROM CHAT;
DELETE FROM CHAT;

INSERT INTO CHAT VALUES(chat_seq.nextval, 1, 'TEST', 'TEST', SYSDATE);