CREATE TABLE CHAT(
	MEMBER_ID			NUMBER	NOT NULL,
	CHAT_LOG_CONTENT	VARCHAR2(100)	NOT NULL,
	CHAT_LOG_DATE		DATE	NOT NULL,
	CONSTRAINT FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);
drop table chat;
SELECT * FROM CHAT;
DELETE FROM CHAT;

INSERT(CHAH_LOG_ID, MEMBER_ID, CHAR_LOG_ANSWER, CHAH_LOG_CONTENT, 
		CHAT_LOG_DATE) 
INTO CHAT 
VALUES(1, 1, 'TEST_CHAR_LOG_ANSWER', 'TEST_CHAH_LOG_CONTENT', SYSDATE);