CREATE TABLE LIKEY(
	LIKEY_ID	NUMBER,
	CONCERT_ID	NUMBER	NOT NULL,
	MEMBER_ID	varchar2(20)	NOT NULL,
	FOREIGN KEY(CONCERT_ID) REFERENCES CONCERT,
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER
	
);

SELECT * FROM LIKEY;
DELETE FROM LIKEY;

create sequence likey_seq increment by 1 start with 1;

INSERT INTO LIKEY VALUES(likey_seq.nextval, 1, 'abc123@mfe.com');