CREATE TABLE LIKEY(
	LIKEY_ID	NUMBER,
	CONCERT_ID	NUMBER	NOT NULL,
	MEMBER_ID	NUMBER	NOT NULL,
	PRIMARY KEY(LIKEY_ID)
);

SELECT * FROM LIKEY;
DELETE FROM LIKEY;

create sequence likey_seq increment by 1 start with 1;

INSERT INTO LIKEY VALUES(likey_seq.nextval, 1, 1);