DROP TABLE REPLY;
drop sequence reply_seq;
CREATE TABLE REPLY(
	REPLY_ID	NUMBER PRIMARY KEY,
	MEMBER_ID	VARCHAR2(50)	REFERENCES MEMBER(MEMBER_ID),
	REPLY_CONTENT	VARCHAR2(200)	,
	REG_DATE 	date		NOT NULL,
	BOARD_RE_REF	NUMBER	NOT NULL,
	FOREIGN KEY(BOARD_RE_REF) REFERENCES BOARD(BOARD_NUM) ON DELETE CASCADE
);
alter table reply modify(member_id varchar2(50));
create sequence reply_seq ;
SELECT * FROM REPLY;
DELETE FROM REPLY;
